name: Splunk.Net
description: A bloggy blog
url: https://blog.splunk.net
safe: true
lsi: true
permalink: /:year/:month/:title/
timezone: America/Denver
markdown: kramdown
category-list: [code, fiction, personal]
excerpt_separator: <!-- more -->
