name: Splunk.Net
description: A place to place my mind
url: https://blog.splunk.net
safe: true
lsi: true
permalink: /:year/:month/:title/
timezone: America/Denver
markdown: kramdown
category-list: [code, fiction, personal, sysadmin]
excerpt_separator: <!-- more -->
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
gems:
  - jekyll-gist

include: [images, javascripts, stylesheets]
exclude: [README.md, CNAME]
